#开发环境
server:
  port: 8120

#Druid Spring Boot Starter#JDBC 配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hello_spring?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: inoriii
    password: 2014212447
    driver-class-name: com.mysql.jdbc.Driver